language: python
python: 2.7
env:
  - TOX_ENV=py27-1.3
  - TOX_ENV=py27-1.4
  - TOX_ENV=py27-1.5
  - TOX_ENV=py27-1.6
  - TOX_ENV=py33-1.5
  - TOX_ENV=py33-1.6
install:
  - pip install tox
script:
  - tox -e $TOX_ENV
